// One-shot migration: parse the PRODUCTS array out of assets/app.js and emit
// a SQL file that seeds the D1 `products` table. Run after `wrangler d1
// execute crystalbrook --file=src/schema.sql` on a fresh database.
//
// Usage:
//   node scripts/seed-d1.mjs > src/seed.sql
//   wrangler d1 execute crystalbrook --remote --file=src/seed.sql

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const APP_JS = resolve(ROOT, 'assets/app.js');

const src = readFileSync(APP_JS, 'utf8');

// We want to run the PRODUCTS literal in a sandboxed context. Easiest reliable
// path: extract the JS expression for `const PRODUCTS = [ ... ];` and eval it
// inside a wrapper that provides the `IMG` and `STD_DESC` constants.
function extractConstant(name) {
  const re = new RegExp(`const\\s+${name}\\s*=\\s*([\\s\\S]*?);`);
  const m = src.match(re);
  if (!m) throw new Error(`Could not find const ${name} in app.js`);
  return m[1].trim();
}

const STD_DESC_EXPR = extractConstant('STD_DESC');
const IMG_EXPR = extractConstant('IMG');

// Pull out just the PRODUCTS array expression (keeping all the IMG+'…'
// concatenations intact, since IMG is in scope below).
const productsMatch = src.match(/const PRODUCTS = (\[[\s\S]*?\n\]);/);
if (!productsMatch) throw new Error('Could not find PRODUCTS array literal');
const PRODUCTS_EXPR = productsMatch[1];

const evalCode = `
  const STD_DESC = ${STD_DESC_EXPR};
  const IMG = ${IMG_EXPR};
  return ${PRODUCTS_EXPR};
`;
const PRODUCTS = new Function(evalCode)();

// Order products in catalogue order — same as the original array order, by
// category. Stored as sort_order = original index, then renumbered per
// category later if needed.
let orderCounter = { saltwater: 0, freshwater: 0, cars: 0, animals: 0, birds: 0, montages: 0 };

function escapeSqlString(s) {
  if (s === null || s === undefined) return 'NULL';
  return `'${String(s).replace(/'/g, "''")}'`;
}
function sqlValue(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return v.toString();
  if (typeof v === 'boolean') return v ? '1' : '0';
  return escapeSqlString(v);
}

const lines = [];
lines.push('-- Generated by scripts/seed-d1.mjs — do not edit by hand.');
lines.push("DELETE FROM products;");
lines.push('');

for (const p of PRODUCTS) {
  const cat = p.cat || 'saltwater';
  const sortOrder = orderCounter[cat] ?? 0;
  orderCounter[cat] = sortOrder + 1;

  const galleryJson = Array.isArray(p.gallery) && p.gallery.length
    ? JSON.stringify(p.gallery)
    : null;

  lines.push(
    `INSERT INTO products (id, name, cat, price, size, image, pimg, badge, meta, description, gallery, draft, sort_order) VALUES (` +
      `${sqlValue(p.id)}, ` +
      `${sqlValue(p.name)}, ` +
      `${sqlValue(p.cat)}, ` +
      `${sqlValue(p.price)}, ` +
      `${sqlValue(p.size)}, ` +
      `${sqlValue(p.image)}, ` +
      `${sqlValue(p.pimg ?? null)}, ` +
      `${sqlValue(p.badge ?? null)}, ` +
      `${sqlValue(p.meta ?? null)}, ` +
      `${sqlValue(p.desc)}, ` +
      `${sqlValue(galleryJson)}, ` +
      `${p.draft ? 1 : 0}, ` +
      `${sortOrder}` +
    `);`
  );
}

console.log(lines.join('\n'));
console.error(`Wrote ${PRODUCTS.length} INSERT statements (${Object.values(orderCounter).reduce((a,b)=>a+b,0)} products).`);
