-- Seed default About-page copy. The storefront falls back to its hardcoded
-- HTML if D1 ever goes quiet, so these values are mainly the starting point
-- Max edits from. Keys map to data-content-key attributes in about.html.

DELETE FROM site_content;

INSERT INTO site_content (key, value) VALUES
  ('about_eyebrow', 'Meet the maker'),
  ('about_h1_main', 'Max White,'),
  ('about_h1_em',   'in his element.'),
  ('about_tagline', 'Bring the world to your walls.'),
  ('about_lede',    'A small workshop in Gordonvale, the smell of resin curing in the Far North Queensland heat, and a stubborn idea — that a wall mount could feel as alive as the fish itself.'),
  ('about_meta_workshop', 'Gordonvale, FNQ'),
  ('about_meta_craft',    'Resin · Hardwood · Print'),
  ('about_meta_runby',    'Max & P. White'),

  ('about_story_h2',   'The story behind <em>Crystal Brook.</em>'),
  ('about_story_p1',   'The brand takes its name from <strong>Crystal Brook</strong> — a freshwater creek that winds out of the Atherton Tableland and runs through the cane country south of Cairns. It''s the same water that gave Max the original spark: a fish, a slab of timber, and the question of how to make one feel as permanent as the other.'),
  ('about_story_p2',   'The studio sits in <strong>Gordonvale</strong>, half an hour''s drive south of Cairns. It''s a one-and-a-half-person operation — Max does the cutting, the mounting and the resin work, and his partner P. helps run the shop side. Workshop visits are by appointment — drop a message or give him a ring and he''ll set a time.'),
  ('about_story_pull', '"Each one is its own piece. No two come out the same — which is the whole point."'),
  ('about_story_p3',   'The product range is deliberately narrow: resin-coated cut-out archival prints mounted on Australian hardwood. <strong>Six categories</strong>, no spillover into homewares or trinkets. Reef fish from the Great Barrier Reef. Freshwater natives from the rivers that feed it. Aussie-built classic cars. Working dogs, wildlife and family pets. Aussie birds. And montages — multi-subject pieces mounted on Australia or Queensland-shaped hardwood backings.'),
  ('about_story_p4',   'What unites them is the finish — every piece spends 48 hours under jewellery-grade epoxy that locks the print, the mount and the maker''s mark under a single lens of glass-clear resin. It''s the kind of thing that looks expensive because it <em>is</em> the kind of thing that lasts a lifetime. A hundred years, if the inks are anything to go by.'),

  ('shipping_eyebrow',      'Shipping'),
  ('shipping_h2',           'Australia-wide. Free, always.'),
  ('shipping_card1_title',  'Free Australia-wide shipping'),
  ('shipping_card1_body',   'Every order ships free to your door, anywhere in Australia. No threshold, no surcharge for the far corners — same delivery to Cairns or Hobart, on us.'),
  ('shipping_card2_title',  'Production: 4–6 weeks'),
  ('shipping_card2_body',   'Each piece is made to order in the Gordonvale workshop. Print, cut, mount, three resin pours, 48-hour cure, signed and numbered. We don''t rush the resin.'),
  ('shipping_card3_title',  'Transit: 3–5 business days'),
  ('shipping_card3_body',   'Once Max packs it (in a custom timber crate for anything over 80 cm), it ships via Australia Post tracked. Tracking link emailed the moment it leaves the workshop.'),
  ('shipping_card4_title',  'International? Drop us a line'),
  ('shipping_card4_body',   'We''ve shipped to NZ, Singapore and the UK. Ask for a quote at <a href="mailto:mandpwhite@optusnet.com.au">mandpwhite@optusnet.com.au</a> with your suburb and the piece you''re after.'),
  ('shipping_callout',      '<strong>Big pieces.</strong> Anything over 100 × 70 cm goes road freight (still tracked, still insured) — allow an extra few days, and we''ll co-ordinate a delivery window with you. Lift gate available on request.'),

  ('pol_crumb',   'Shipping & Returns'),
  ('pol_eyebrow', 'The fine print, in plain English'),
  ('pol_h1',      'Shipping & Returns.'),
  ('pol_lede',    'No legalese. No surprises. Here''s exactly how Max ships your piece, and what happens if anything goes sideways.'),
  ('pol_jump1',   'Shipping →'),
  ('pol_jump2',   'Returns →'),
  ('pol_jump3',   'Workmanship guarantee →'),
  ('pol_jump4',   'Custom commissions →'),

  ('returns_eyebrow',     'Returns'),
  ('returns_h2',          'If it arrives wrong, we make it right.'),
  ('returns_card1_title', 'Damaged in transit'),
  ('returns_card1_body',  'Send a photo within <strong>72 hours of delivery</strong> and we''ll replace the piece at no cost — Max keeps the broken one for parts. Couriers happen. We''ve got it covered.'),
  ('returns_card2_title', 'Wrong piece sent'),
  ('returns_card2_body',  'If we ship the wrong fish (or wrong timber, or wrong size), we cover return postage and rush a corrected piece to the front of the queue.'),
  ('returns_card3_title', 'Changed your mind'),
  ('returns_card3_body',  'Standard catalogue pieces (not custom commissions): you can return within <strong>14 days of delivery</strong>. Piece must be unhung and in original packaging. Return postage on you, and a 15% restocking fee covers our shipping cost out + back. The rest is refunded to your original payment within 5 business days.'),
  ('returns_card4_title', 'Custom commissions'),
  ('returns_card4_body',  'Once Max has printed your one-off, it''s yours. Deposits are <strong>fully refundable up to print stage</strong> (usually 5 business days from order). After that, we''ll work with you on revisions but can''t refund the print + timber cost.'),

  ('guarantee_eyebrow',     'Workmanship guarantee'),
  ('guarantee_h2',          'If the resin yellows or the timber cracks — we''ll make it right.'),
  ('guarantee_lede',        'Every Crystal Brook piece is built to outlive its owner. We use UV-stabilised, jewellery-grade two-part epoxy and Australian hardwoods that have been seasoned for years. If anything fails through manufacturing, you''ve got Max''s word in writing.'),
  ('guarantee_item1_title', 'Resin yellowing'),
  ('guarantee_item1_body',  'Lifetime cover. Send a photo, we''ll re-pour or rebuild it. Just keep it out of direct equatorial sun for 6+ hours daily.'),
  ('guarantee_item2_title', 'Print fading'),
  ('guarantee_item2_body',  'Archival pigment ink rated 100+ years indoors. If it fades inside that window from anything other than direct sun, we''ll reprint and remount.'),
  ('guarantee_item3_title', 'Timber cracking / warping'),
  ('guarantee_item3_body',  '5-year cover under normal indoor conditions (heated/cooled rooms, not bathrooms). After 5 years, rebuild at cost.'),
  ('guarantee_item4_title', 'Mounting hardware failure'),
  ('guarantee_item4_body',  'Lifetime — heavy-duty D-rings rated 4× the piece weight come standard.'),

  ('biz_name',     'Crystal Brook Wall Mounts'),
  ('biz_abn',      '00 000 000 000'),
  ('biz_email',    'mandpwhite@optusnet.com.au'),
  ('pay_currency', 'AUD'),
  ('pay_tax',      'GST 10%'),
  ('ship_au',      'Free — every order'),
  ('ship_intl',    'Quote on request'),

  ('commissions_eyebrow',     'Custom commissions'),
  ('commissions_h2',          'Your idea, on the wall.'),
  ('commissions_lede',        'A few notes on how custom pieces work:'),
  ('commissions_card1_title', 'Working from your idea'),
  ('commissions_card1_body',  'Max prints from your <em>idea</em>, not from your photographs. Tell him the subject — a particular reef fish, a working dog, a classic ute — and he''ll source or produce a high-resolution master ready for the resin treatment. No need to send your own photos; he prefers to start fresh.'),
  ('commissions_card2_title', 'Approval before pour'),
  ('commissions_card2_body',  'Max emails a digital mockup before he prints. You sign off, then production begins. No surprises.'),
  ('commissions_card3_title', 'Lead time'),
  ('commissions_card3_body',  '5–7 weeks for commissions (one extra week for the back-and-forth). Faster turnaround can be arranged for an extra fee.'),
  ('commissions_card4_title', 'Permissions'),
  ('commissions_card4_body',  'If the subject is someone else''s pet, vehicle or artwork, you confirm you have permission to commission a print of it. Crystal Brook keeps no rights to the finished piece — it''s yours.'),
  ('commissions_cta_title',   'Still got questions?'),
  ('commissions_cta_body',    'Easiest way is a phone call to <a href="tel:+61740561887">(07) 4056 1887</a> or an email to <a href="mailto:mandpwhite@optusnet.com.au">mandpwhite@optusnet.com.au</a>. Max usually replies same-day.'),
  ('commissions_cta_button',  'Get in touch →');
